export enum MeasurementUnitActionType {
  SET_UNIT_CELSIUS = "SET_UNIT_CELSIUS",
  SET_UNIT_FAHRENHEIT = "SET_UNIT_FAHRENHEIT",
}

export enum WeatherDataActionType {
  WEATHER_DATA_IDLE = "WEATHER_DATA_IDLE",
  WEATHER_DATA_LOADING = "WEATHER_DATA_LOADING",
  WEATHER_DATA_LOADED = "WEATHER_DATA_LOADED",
  WEATHER_DATA_ERROR = "WEATHER_DATA_ERROR",
}

export enum SearchFieldActionType {
  SET_SEARCH_FIELD_VALUE = "SET_SEARCH_FIELD_VALUE",
  SET_SEARCH_FIELD_VALIDATION = "SET_VALIDATION",
  CLEAR_SEARCH_FIELD_VALIDATION = "CLEAR_VALIDATION",
}

export enum FavouriteActionType {
  ADD_FAVOURITE = "ADD_FAVOURITE",
  REMOVE_FAVOURITE = "REMOVE_FAVOURITE",
  REFRESH_FAVOURITES = "REFRESH_FAVOURITES",
}
